apiVersion: v1
kind: Pod
metadata:
  name: monitor
  labels:
    app: monitor
spec:
  containers:
    - name: monitor
      image: albertzuo/monitor:v1.0.0
      imagePullPolicy: IfNotPresent

  restartPolicy: Always
